[package]
name = "secrez-rust"
version = "0.1.0"
authors = ["Francesco Sullo <francesco@sullo.co>"]
edition = "2018"

[dependencies]
rand = "0.7"
rust-crypto = "^0.2"
rpassword = "4.0"
dirs = "2.0"
rustyline = "5.0.1"
colored = "1.8.0"
hex-literal = "0.2.0"
block-modes = "0.3.3"
aes-soft = "0.3.3"
